spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/tqi?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: 142536
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace

